"""added materia to Tarea

Revision ID: 0e196468cb16
Revises: fb8d4c3f1f54
Create Date: 2026-10-05 20:58:24.283634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e196468cb16'
down_revision: Union[str, Sequence[str], None] = 'fb8d4c3f1f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_column('materia')

    # ### end Alembic commands ###
