"""added materia relationship

Revision ID: 5d4c2e3559aa
Revises: 0e196468cb16
Create Date: 2026-10-05 21:31:05.910139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "5d4c2e3559aa"
down_revision: Union[str, Sequence[str], None] = "0e196468cb16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materia",
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("anio", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tarea", schema=None) as batch_op:
        batch_op.add_column(sa.Column("materia_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_tarea_materia_id", "materia", ["materia_id"], ["id"]
        )
        batch_op.drop_column("materia")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tarea", schema=None) as batch_op:
        batch_op.add_column(sa.Column("materia", sa.VARCHAR(), nullable=True))
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("materia_id")

    op.drop_table("materia")
    # ### end Alembic commands ###
